AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI Application

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.main.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseURL
          # Other environment variables
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
